import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import {Montserrat_Subrayada} from "@next/font/google";

const montserrat = Montserrat_Subrayada({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
